version: "3.8"

services:
  art_kolkata_frontend:
    build: ./frontend
    image: art_kolkata_frontend
    container_name: art_kolkata_frontend
    expose:
      - "3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - art_kolkata_api_1
      - art_kolkata_upload_api_1
    networks:
      - art_kolkata_newtork
      - shared_network

  art_kolkata_crm:
    build: ./cms
    container_name: art_kolkata_crm
    image: art_kolkata_crm
    expose:
      - "80"
    env_file:
      - ./cms/.env
    depends_on:
      - art_kolkata_api_1
      - art_kolkata_upload_api_1
    networks:
      - art_kolkata_newtork
      - shared_network

  art_kolkata_api_1:
    build: ./api
    container_name: art_kolkata_api_1
    image: art_kolkata_api_1
    expose:
      - "3000"
    env_file:
      - ./api/.env
    depends_on:
      - art_kolkata_postgres_1
    volumes:
      - ./logs/api-logs:/app/logs
    networks:
      - art_kolkata_newtork
      - shared_network

  art_kolkata_upload_api_1:
    build: ./upload
    container_name: art_kolkata_upload_api_1
    image: art_kolkata_upload_api_1
    expose:
      - "3000"
    env_file:
      - ./upload/.env
    volumes:
      - ./uploaded-files/uploads:/app/uploads
      - ./uploaded-files/private:/app/private
    depends_on:
      - art_kolkata_postgres_1
    networks:
      - art_kolkata_newtork
      - shared_network

  art_kolkata_postgres_1:
    image: postgres:17.4-alpine
    container_name: art_kolkata_postgres_1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - art_kolkata_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - art_kolkata_newtork
      - shared_network

  # COMMENT OUT BECAUSE i am uploading this in a vps where nginx is the default server
  # nginx_1:
  #   image: nginx:latest
  #   container_name: nginx_1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/${NGINX_CONF_FILE_NAME}:/etc/nginx/conf.d/default.conf
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - c1_frontend_1
  #     - c1_api_1
  #     - c1_upload_api_1
  #     - art_kolkata_postgres_1
  #   restart: always
  #   networks:
  #     - art_kolkata_newtork

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: >
  #     sh -c "while true; do
  #       certbot renew --webroot -w /var/www/certbot --quiet \
  #       --deploy-hook 'docker exec nginx_1 nginx -s reload';
  #       sleep 12h;
  #     done"
  #   depends_on:
  #     - nginx_1

volumes:
  art_kolkata_pg_data:

networks:
  art_kolkata_newtork:
    driver: bridge
  shared_network:
    external: true
