version: "3.8"

networks:
  client_4_custom_network:
    driver: bridge

services:
  c4_frontend_1:
    build:
      context : 
        ./frontend
      args :
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    container_name: c4_frontend_1
    ports:
      - "${FRONTEND_HOST_PORT}:3000"
    env_file:
      - ./envs/.frontend.env
    depends_on:
      - c4_api_1
      - c4_upload_api_1
    networks:
      - client_4_custom_network

  c4_crm_1:
    build: 
      context : 
        ../admin-panel/crm
      args : 
        VITE_API_BASE_URL : ${VITE_API_BASE_URL}
        VITE_API_UPLOAD_BASE_URL : ${VITE_API_UPLOAD_BASE_URL}
    container_name: c4_crm_1
    ports:
      - "${CRM_HOST_PORT}:80"
    env_file:
      - ./envs/.crm.env
    depends_on:
      - c4_api_1
      - c4_upload_api_1
    networks:
      - client_4_custom_network

  c4_api_1:
    build: ../admin-panel/api
    container_name: c4_api_1
    ports:
      - "${API_HOST_PORT}:3000"
    env_file:
      - ./envs/.api.env
    environment:
        POSTGRES_URL: ${POSTGRES_CONNECTION_URL}
    depends_on:
      - c4_postgres_1
    volumes:
      - ./logs/api-logs:/app/logs
    networks:
      - client_4_custom_network

  c4_upload_api_1:
    build: ../admin-panel/upload
    container_name: c4_upload_api_1
    ports:
      -  "${UPLOAD_HOST_PORT}:3000"
    env_file:
      - ./envs/.upload.env
    volumes:
      - ./uploaded-files/uploads:/app/uploads
      - ./uploaded-files/private:/app/private
    depends_on:
      - c4_postgres_1
    networks:
      - client_4_custom_network

  c4_postgres_1:
    image: postgres:17.4-alpine
    container_name: c4_postgres_1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - client_4_pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - client_4_custom_network

 # COMMENT OUT BECAUSE i am uploading this in a vps where nginx is the default server
  # nginx_1:
  #   image: nginx:latest
  #   container_name: nginx_1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/${NGINX_CONF_FILE_NAME}:/etc/nginx/conf.d/default.conf
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - c4_frontend_1
  #     - c4_api_1
  #     - c4_upload_api_1
  #     - c4_postgres_1
  #   restart: always
  #   networks:
  #     - client_4_custom_network

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: >
  #     sh -c "while true; do
  #       certbot renew --webroot -w /var/www/certbot --quiet \
  #       --deploy-hook 'docker exec nginx_1 nginx -s reload';
  #       sleep 12h;
  #     done"
  #   depends_on:
  #     - nginx_1

volumes:
  client_4_pg_data: