import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono, Montserrat, Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import FloatingCart from "./Component/trending/FloatingCart";
import CartDrawer from "./Component/CartDrawer";
import { QueryClientWrapper } from "./Component/QueryClientWrapper";
import { ToastContainer } from "react-toastify";
import Marquee from "@/Component1/Marquee";
import Navbar from "@/Component1/layout/Navbar";
import SubNav from "@/Component1/layout/SubNav";
import MainWrapper from "./Component/MainWrapper";
import Footer from "@/Component1/layout/Footer";
import MobileBottomNav from "@/Component1/layout/MobileBottomNav";
import FloatingWhatsApp from "@/Component1/FloatingWhatsApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400"],
});

const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Art Kolkata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${ubuntuMono.variable} antialiased`}
      >
        <div id="google_translate_element" style={{ display: "none" }}></div>
        <Script
          src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="afterInteractive"
        />
        <Script id="google-translate-init" strategy="beforeInteractive">
          {`
            if (typeof Node === 'function' && Node.prototype) {
              const originalRemoveChild = Node.prototype.removeChild;
              Node.prototype.removeChild = function(child) {
                if (child.parentNode !== this) {
                  return child;
                }
                return originalRemoveChild.apply(this, arguments);
              };
            
              const originalInsertBefore = Node.prototype.insertBefore;
              Node.prototype.insertBefore = function(newNode, referenceNode) {
                if (referenceNode && referenceNode.parentNode !== this) {
                  return newNode;
                }
                return originalInsertBefore.apply(this, arguments);
              };
            }

            function googleTranslateElementInit() {
              new window.google.translate.TranslateElement(
                { pageLanguage: 'en', autoDisplay: false },
                'google_translate_element'
              );
            }
          `}
        </Script>
        <QueryClientWrapper>
          <ToastContainer position="top-center" autoClose={2000} />

          {/* <Marquee /> */}
          <Navbar />
          <SubNav />
          {/* <Header /> */}
          <MainWrapper>{children}</MainWrapper>
          <Footer />
          <MobileBottomNav />
          {/* <Footer /> */}
          <FloatingWhatsApp />
        </QueryClientWrapper>
      </body>
    </html>
  );
}
