upstream api_servers {
    server 127.0.0.1:3000;
}

upstream upload_servers {
    server 127.0.0.1:3000;
}

server {
    listen 80;
    server_name c3.ommnews.in www.c3.ommnews.in crm-c3.ommnews.in api-c3.ommnews.in upload-c3.ommnews.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        # return 301 https://$host$request_uri;
        proxy_pass http://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name c3.ommnews.in;

    ssl_certificate /etc/letsencrypt/live/c3.ommnews.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/c3.ommnews.in/privkey.pem;

    location / {
        proxy_pass http://tc_frontend_1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Disable buffering for streaming support
        proxy_buffering off;
        proxy_set_header X-Accel-Buffering no;
    }
}

server {
    listen 443 ssl;
    server_name www.c3.ommnews.in;

    ssl_certificate /etc/letsencrypt/live/c3.ommnews.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/c3.ommnews.in/privkey.pem;

    location / {
        return 301 https://c3.ommnews.in$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name crm-c3.ommnews.in;

    ssl_certificate /etc/letsencrypt/live/c3.ommnews.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/c3.ommnews.in/privkey.pem;

    # Serve Vite build folder
    root /var/www/crm;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;  # SPA mode
    }
}

server {
    listen 443 ssl;
    server_name api-c3.ommnews.in;

    client_max_body_size 10M;

    ssl_certificate /etc/letsencrypt/live/seiedutrust.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/seiedutrust.com/privkey.pem;

    location / {
        # limit_req zone=api_zone burst=30 nodelay;  # Apply rate limit here
        proxy_pass http://api_servers;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name upload-c3.ommnews.in;

    client_max_body_size 200M;

    ssl_certificate /etc/letsencrypt/live/c3.ommnews.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/c3.ommnews.in/privkey.pem;

    location / {
        # limit_req zone=upload_zone burst=5 nodelay;  # Apply rate limit here
        proxy_pass http://upload_servers;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

