upstream api_servers_c4 {
    server 127.0.0.1:4008;
}

upstream upload_servers_c4 {
    server 127.0.0.1:5008;
}

server {
    listen 80;
    server_name c4.ommnews.in www.c4.ommnews.in crm-c4.ommnews.in api-c4.ommnews.in upload-c4.ommnews.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name c4.ommnews.in;

    ssl_certificate /etc/letsencrypt/live/c4.ommnews.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/c4.ommnews.in/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:3008;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Disable buffering for streaming support
        proxy_buffering off;
        proxy_set_header X-Accel-Buffering no;
    }
}

# server {
#     listen 443 ssl;
#     server_name www.c4.ommnews.in;

#     ssl_certificate /etc/letsencrypt/live/c4.ommnews.in/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/c4.ommnews.in/privkey.pem;

#     location / {
#         return 301 https://c4.ommnews.in$request_uri;
#     }
# }

server {
    listen 443 ssl;
    server_name crm-c4.ommnews.in;

    ssl_certificate /etc/letsencrypt/live/c4.ommnews.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/c4.ommnews.in/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:6008;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Disable buffering for streaming support
        proxy_buffering off;
        proxy_set_header X-Accel-Buffering no;
    }
}

server {
    listen 443 ssl;
    server_name api-c4.ommnews.in;

    client_max_body_size 10M;

    ssl_certificate /etc/letsencrypt/live/c4.ommnews.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/c4.ommnews.in/privkey.pem;

    location / {
        # limit_req zone=api_zone burst=30 nodelay;  # Apply rate limit here
        proxy_pass http://api_servers_c4;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name upload-c4.ommnews.in;

    client_max_body_size 200M;

    ssl_certificate /etc/letsencrypt/live/c4.ommnews.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/c4.ommnews.in/privkey.pem;

    location / {
        # limit_req zone=upload_zone burst=5 nodelay;  # Apply rate limit here
        proxy_pass http://upload_servers_c4;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}